remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Cardiovascular Disease Biomarker Analysis]
description: [Analysis and prediction of homocysteine among non-smoking participants of the NHANES 2005-2006 Cohort Study]