remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Cardiovascular Disease Biomarker Analysis]
description: [An analysis of homocysteine, a biomarker for cardiovascular disease, among non-smoker partipants from the NHANES 2005-2006 cohort
By Amber Campbell]